### ISSUE TITLE
Using CNVkit files 

### ISSUE THREAD

**Issue by yisu-li** [lima1/PureCN#53]
Hi there,

I was trying to run pureCN by using CNVkit segmentation, but I got the following error.
`Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 9: negative widths are not allowed
Calls: runAbsoluteCN ... GRanges -> new_GRanges -> IRanges -> solveUserSEW0 -> .Call2
Execution halted`

Do you have any inside which file is causing the problem here?

Here is the command I ran.
`$PURECN/PureCN.R --out $output_dir/HCC1143_pureCN/ --sampleid HCC1143 --segfile HCC1143.cnvkit.seg --vcf HCC1143.mutect_1.1.4.vcf --intervals $PURECN/reference_files/baits_hg19_intervals.txt --genome hg19`

Secondly, in the Quick Start page 6, I should include a normal panel VCF in generate a normal DB specific to the assay.  We routinely run GATK3 Haplotypecaller for normal samples.  Is it sufficient to concatenate all the variants from normal samples into one VCF or do I need to remove the duplicated variants?

Lately,  I was trying to run PureCN for coverage analysis, but it couldn't go any further due to X11 display problem when it was generate the png file.  Is it possible to run the coverage analysis without X11 display connection?

Thanks,
Yisu

**Comment by lima1** [comment]
Hi Yisu,

can you try the latest GitHub version (see README for install)? I suspect that the interval file was generated using a stranded baits file. That bug was fixed in the developer version a while ago. Latest GitHub will become new stable in 2 days.

Not sure what causes the X11 problems. Can you post the full error message, including the commands used?

Best,
Markus

**Comment by lima1** [comment]
Regarding the normal panel, see the FAQ in the vignette how to generate it using GATK3.

**Comment by yisu-li** [comment]
Hi Markus,

Thank you so much for the reply.  I am still getting the same error after updating my version to the latest dev, so I assume my baits file might have problem. 
`Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : solving row 9: negative widths are not allowed Calls: runAbsoluteCN ... GRanges -> new_GRanges -> IRanges -> solveUserSEW0 -> .Call2 Execution halted`

I generated the baits file using the IntervalFile.R, and the file looks like so.  I checked all regions,  end positions are always greater in number than the corresponding start positions.  Any other suggestions please?   Thanks.

> $ head /home/yisuli/R_modules_pureCN/PureCN/reference_files/baits_hg19_intervals.txt 
Target	gc_bias	mappability	reptiming	Gene	on_target
1:1309171-1309292:+	0.60655737704918	1	81.0584852010897	.	TRUE
1:1309370-1309602:+	0.618025751072961	1	81.0584852010897	.	TRUE
1:1309603-1309835:+	0.703862660944206	1	81.0584852010897	.	TRUE
1:1310075-1310146:+	0.652777777777778	1	81.0584852010897	.	TRUE
1:2488094-2488182:+	0.662921348314607	1	65.6359117715666	.	TRUE
1:2489155-2489283:+	0.643410852713178	1	65.6359117715666	.	TRUE
1:2489772-2489917:+	0.602739726027397	1	65.6359117715666	.	TRUE
1:2491252-2491427:+	0.693181818181818	1	65.6359117715666	.	TRUE
1:2492053-2492163:+	0.585585585585586	1	65.6359117715666	.	TRUE

**Comment by lima1** [comment]
Can you re-run IntervalFile.R with the latest version? 

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("PureCN", version = "3.8")

Like I said, this is caused by a stranded baits file, which PureCN 1.12.1 or (1.13.5 in devel) should handle correctly.

**Comment by lima1** [comment]
Once the baits file is correct (no ":+" or ":-" behind the chr:start-stop), you'll need to restart from scratch, recalculating coverages and rebuilding the normal database. Sorry if this was not clear.

**Comment by yisu-li** [comment]
Thank you, but I am now getting missing a 'Gene' column error.  

> FATAL [2018-11-11 22:53:47] This function requires gene-level calls. Please add a column 'Gene' 
FATAL [2018-11-11 22:53:47] containing gene symbols to the interval.file. 

The baits file is now looking like so.

> Target	gc_bias	mappability	reptiming	Gene	on_target
1:10501-176868	0.42972807270629	0.150027171902202	63.0937528664896	.	FALSE
1:227918-267127	0.392527416475389	0.148528792503623	57.654866397971	.	FALSE
1:318220-470819	0.425858453473132	0.125564267167629	40.3966851187224	.	FALSE
1:521869-718568	0.434031520081342	0.143525078563553	63.4419558307912	.	FALSE
1:718569-915269	0.519524557577236	0.424118522121566	73.59854050438	.	FALSE
1:915270-1111969	0.611123538383325	0.285803345980904	77.9070630718773	.	FALSE
1:1111970-1308670	0.619244436988119	0.335034270783464	79.9097352987862	.	FALSE
1:1309171-1309292	0.60655737704918	1	81.0584852010897	.	TRUE
1:1309370-1309602	0.618025751072961	1	81.0584852010897	.	TRUE

Should I ignore this error?  When creating the baits file, the script was trying to download file TxDb.Hsapiens.UCSC.hg19.knownGene’, but I don't know where it downloaded the file.  Does it seem to you that the file was not used correctly?

Thanks,
Yisu

**Comment by lima1** [comment]
That's an R package, open R and install it with.

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene", version = "3.8")

Yes, PureCN shouldn't crash without the Gene column, I'll fix this soon. But simply install the package, rerun IntervalFile.R and you should be all good. No need to recreate coverage files or normal database.

**Comment by lima1** [comment]
Closing due to inactivity.
